name: Compilar APK de SULIN

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permiso a Gradle
        working-directory: SulinApp
        run: chmod +x ./gradlew

      - name: Compilar APK
        working-directory: SulinApp
        run: ./gradlew assembleDebug

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: APK-SULIN
          path: SulinApp/app/build/outputs/apk/debug/*.apk
